config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :workouts do
    resources :worksets
  end

  resources :exercises

  get 'workouts/:id/next', to: 'workouts#next'

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_many :worksets
  has_many :workouts, through: :worksets

  validates_presence_of :name

  scope :exercise_order, -> { order("name")}

  # def self.exercise_order
  #   order("name")
  # end

  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :workouts
  has_many :exercises, through: :workouts

  def self.from_omniauth(auth)
    # Either create a User record or update it based on the provider (Google) and the UID
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
 end
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :worksets, inverse_of: :workout, dependent: :destroy
  has_many :exercises, through: :worksets
  accepts_nested_attributes_for :worksets, allow_destroy: true

  validates :name, presence: true

  def exercise_num(num)
    num.to_i.times { self.worksets.build.build_exercise } if num
  end


  def delete_worksets
    self.worksets.destroy_all
  end

  def next
    workout = Workout.where("id > ?", id).first
    if workout
      workout
    else
      Workout.first
    end
  end
end

app/models/workset.rb
class Workset < ApplicationRecord
  belongs_to :exercise
  belongs_to :workout
  accepts_nested_attributes_for :exercise, allow_destroy: true


  def exercise_attributes=(exercise)
    self.exercise = Exercise.find_or_create_by(name: exercise["name"])
    self.exercise.update(exercise)
  end
  # find or create by name for Exercise

  validates_presence_of :sets
  validates_presence_of :reps
  validates_presence_of :weight
end

app/controllers/Users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
  
    if @user.persisted?
      sign_in @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
    end
     redirect_to root_path
    end
 end

app/controllers/application_controller.rb
# require 'google/apis/people_v1'
# require 'google/api_client/client_secrets.rb'


class ApplicationController < ActionController::Base

  # app/controller/application_controller.rb

  # People = Google::Apis::PeopleV1
  # def contacts
  #   secrets = Google::APIClient::ClientSecrets.new(
  #     {
  #       "web" =>
  #         {
  #           "access_token" => current_user.token,
  #           "refresh_token" => current_user.refresh_token,
  #           "client_id" => Rails.application.credentials.google[:client_id],
  #           "client_secret" => Rails.application.credentials.google[:client_secret]
  #         }
  #     }
  #   )
  #   service = People::PeopleServiceService.new
  #   service.authorization = credentials.to_authorization
  #   response = service.list_person_connections(
  #     'people/me',
  #      person_fields: ['names', 'emailAddresses', 'phoneNumbers']
  #   )
  #   render json: response
  # end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
   before_action :find_exercise, only: [:show, :destroy]

  def index
    @exercises = Exercise.all.exercise_order
  end

  def show
  
  end

  def destroy
    @exercise.destroy
    redirect_to exercises_path
  end

  private

  def find_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:name)
  end



end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

 def sign_up_params
  params.require(:user).permit(:username, :email, :password, :password_confirmation)
 end

 def account_update_params
  params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
 end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :edit, :update, :destroy, :next]

  def index
    @workouts = Workout.all
    respond_to do |f|
      f.html
      f.json {render json: @workouts}
    end
    @workouts = current_user.id
  end

  
  def new
    @workout = Workout.new
    @workout.exercise_num(params[:exercise_num])
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user_id = current_user.id
    if @workout.valid?
      @workout.save
      render json: @workout
    else
      flash[:errors] = @workout.errors.full_messages
      redirect_to new_workout_path
    end
  end

  def next
    @next_workout = @workout.next
    render json: @next_workout
  end
  
  def show
    respond_to do |f|
      f.html
      f.json {render json: @workout}
    end
  end
  
  def edit
  end

  def update
    @workout.assign_attributes(workout_params)
    if @workout.valid?
      @workout.delete_worksets
      @workout.update_attributes(workout_params)
      # @workout.save
      redirect_to @workout
    else
      flash[:errors] = @workout.errors.full_messages
      redirect_to edit_workout_path(@workout)
    end
  end

  def destroy
    @workout.destroy
    redirect_to @workout
  end

  private

  def find_workout
    @workout = Workout.find(params[:id])
    respond_to do |f|
      f.html
      f.json {render json: @workout}
    end
    @user = @workout.user
  end

  def workout_params
    params.require(:workout).permit(:id,
      :name, :date, :duration, :notes,
      worksets_attributes: [:_destroy, :sets, :reps, :weight,
        exercise_attributes: [:_destroy, :name]
        ])
  end
end

app/controllers/worksets_controller.rb
class WorksetsController < ApplicationController

before_action :find_workset, only: [:show, :edit, :update, :destroy]

def index
  @workout = Workout.find(params[:workout_id])
  @worksets = @workout.worksets
end

def new
  @workout = Workout.find(params[:workout_id])
  @workset = @workout.worksets.build
  @workset.build_exercise

end

def show
end

def create
  @workout = Workout.find(params[:workout_id])
  # binding.pry
  @workset = @workout.worksets.build(workset_params)
  if @workset.save
    redirect_to workout_workset_path(@workout, @workset)
  else
    render :new
  end
end

private

def find_workset
  @workset = Workset.find(params[:id])
  @workout = @workset.workout
end

def workset_params
  params.require(:workset).permit(
    :sets, :reps, :weight,
      exercise_attributes: [:_destroy, :name])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workout_helper.rb
module WorkoutHelper

def user_reps(workouts, user)
  final_string = ""
  workouts.each do |workout|

    if user.id == workout.user_id

      final_string << '<tr><td style="text-align: center">' + (link_to workout.name, workout, class:"special-links") + '</td>
                         <td style="text-align: center">' + (workout.date.strftime('%A, %B, %d')) + '</td>'
    end
  end
  final_string.html_safe
end

end

app/views/exercises/edit.html.erb
<h1>Edit Exercise</h1>

<%= render partial:'form', locals:{exercise: @exercise, workout: @exercise.workout} %>

<%= form_tag(exercise_path(@exercise),method: :delete) do %>
		<%= submit_tag "Delete Exercise" %>
<% end %>

app/views/exercises/index.html.erb
<section class="hero is-dark is-bold">
  <div class="hero-body">
  <h3 class="title">
        EXERCISES
      </h3>
  <div class="container">
    <div class="columns is-left">
      <div class="column is-6">
      <div class="exercises">
       <h4>Filter By Exercise</h4>
      <input type="text" id="myInput" class="input is-fullwidth" onkeyup="myFunction()" placeholder="Search by ecercise name...">
       <br>
        <table id="exerciseTable" class="table is-bordered is-narrow is-hoverable is-fullwidth">
          <thead>
            <tr>
          <th style="text-align: left">Exercise List</th>
         
        </tr>
          </thead>
          <tbody>
            <% @exercises.each do |exercise| %>
            <tr>
              <td style="text-align: left"> <%= link_to exercise.name, exercise, class:"special-links" %>  </td>
           
              <% end %>

            </tr>
          </tbody>
        </table>

        
<script>
function myFunction() {
  // Declare variables 
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("exerciseTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    } 
  }
}




function checkExercise() {
  // Get the checkbox
  var checkBox = document.getElementById("myCheck");
  // Get the output text
  var button = document.getElementById("button");

  // If the checkbox is checked, display the output text
  if (checkBox.checked == true){
    button.style.display = "block";
  } else {
    button.style.display = "none";
  }
}
</script>
      </div>
    </div>
  </div>
  </div>
    </div>
  </div>

app/views/exercises/show.html.erb
<% content_for :header do %>
<section class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h3 class="title">
        <%= @exercise.name %>
      </h3>
      <h4 class="subtitle">

        </h4>
    </div>
  </div>
</section>
<% end %>

<br>
<h4>Workouts that include this exercise.</h4>
   <%=@workouts.name%>


<%= link_to "Delete", exercise_path(@exercise),
            method: :delete,
            data: {confirm: "Are you sure you want to delete?"},
            class:"button is-dark is-rounded" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <head>
    <title>X-ercise</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-white is-fixed-top" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-3 is-white">X-ercise </h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
       <% if user_signed_in? %>
      <div id="navbar" class="navbar-menu">

    <div class="navbar-start">
      <a class="navbar-item"<%= link_to 'New Workout', new_workout_path%>
       </a>

      <a id=all_workouts class="navbar-item"<%= link_to 'My Workouts', workouts_path%>
      </a>

      <a class="navbar-item" <%= link_to 'Exercises', exercises_path%>
        </a>

        <button class="filter">Filter Workouts</button>
          <%end%>
        </div>
    </div>



        <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">

              <div class="col-xs-6 text-right">

                <% if user_signed_in? %>
                <div class="navbar-item has-dropdown is-hoverable">
                     <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                     <div class="navbar-dropdown is-right">
                       <%= link_to current_user.username, edit_user_registration_path, class:"navbar-item" %>
                       <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                     </div>
                   </div>

            <% else %>
              <%= link_to "Sign In", new_user_session_path, class:"button is-dark is-rounded" %>
              <%= link_to "Sign up", new_user_registration_path, class:"button is-dark is-rounded "%>
             
          <%end%>





            </div>
          </div>
        </div>
    </div>
  </nav>
   
  <%= yield(:header) %>

  <div id="output" class="container">

    <%= yield %>

  </div>

  </body>
</html>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>


<section class="hero is-dark is-bold is-fullheight">
  <div class="hero-body">
    <div class="columns is-vcentered">
  <div class="column is-4">
      <h3 class="title">
        X-ercise
      </h3>
      <h4 class="subtitle">
        Welcome to your personal workout tracker.
        </h4></div>
  <div class="column is-8"><%= image_tag('gym.jpg', class: 'img-responsive') %></div>
  </div>

    </div>

</section>

app/views/workouts/_exercise_fields.html.erb
<div class="input-group exercise-form">

  <%= f.input :name, placeholder:"Exercise Name", required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false%>





</div>

app/views/workouts/_form.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-left">
      <div class="column is-4">
        <div class="workout-form-group">
  <%= simple_form_for (@workout) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="field">
      <div class="control">
      
        <%= f.input :name, placeholder:"Workout Name", required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false %>
      </div>
    </div>

     <div class="field">
      <div class="control">
      
        <%= f.input :date, as: :date, required: true, wrapper: false, autofocus: true, input_html: { class: "input is-rounded"}%>
      </div>
    </div>


    <div class="field">
    <div class="control">
    
      <%= f.input :duration, placeholder:"Length of Workout", required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false%>
    </div>
  </div>

   <div class="field">
    <div class="control">
    
      <%= f.input :notes, placeholder:"Notes", required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false%>
    </div>
  </div>


  <br>
  <h3 class="container"><strong>EXERCISES</strong></h3>
  
  <%= f.fields_for :worksets do |w| %>
    <%= w.fields_for :exercise do |exercise_form| %>
     <div class="field">
    <div class="control">
      <%= render 'exercise_fields', f: exercise_form %>
    <% end %>
    </div>
    </div>
     <div class="field">
    <div class="control">
    <%= w.input :sets, placeholder:"Sets",  required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false %>
    </div>
</div>
<div class="field">
    <div class="control">
    <%= w.input :reps, placeholder:"Reps",  required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false %>
       </div>
   </div>
    <div class="field">
    <div class="control">
    <%= w.input :weight, placeholder:"Weight",  required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false %>
       </div>
   </div>
  <% end %>

  <br></br>
  <%=  f.button :submit, "Submit", class:"button is-light is-rounded" %>

<% end %>
</div>
</section>

app/views/workouts/_reps.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th style="text-align: center">Workout</th>
      <th style="text-align: center">Date</th>

    </tr>
  </thead>
  <tbody>
    <%=user_reps(@workouts, current_user)%>

    
    </tr>
  </tbody>
</table>
</div>
</div>
</div>

app/views/workouts/_workset_fields.html.erb
<div class='input-group workset-form'>
  <%= f.input :sets, placeholder:"Sets",  required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label"} %>
  <%= f.input :reps, placeholder:"Reps",  required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
  <%= f.input :weight, placeholder:"Weight",  required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>

</div>

app/views/workouts/edit.html.erb
<section class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h3 class="title">
        EDIT WORKOUT
      </h3>
 


        <%= render 'form' %>
   </div>
  </div>
</section>

app/views/workouts/index.html.erb
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script>
  $(document).ready(function() {
  
    //To show rows
     $(".showrows").click(function () {
     $(".test  .1").show(1000)
   });  
       //To hide rows
     $(".hiderows").click(function () {
     $(".test  .1").hide("slow")
   }); 
});
</script>



<section class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h3 class="title">
        WORKOUT LOGS
      </h3>
      <h4 class="subtitle">
        Total Workouts Completed by: <%=current_user.username%>
        </h4>
    <div class="columns is-left">
      <div class="column is-6">



        <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
          <thead>
            <tr>
              <th colspan="4" style="text-align: left">WORKOUTS</th>
            </tr>
         
            <button class="filter">Filter Workouts</button>>
            <br>
            <% current_user.workouts.each do |workout| %>
            <tr>
              <td colspan="4"><strong style="font-size: 20px"><%= link_to workout.name, workout, class:"special-links" %></strong><br>
               <%= workout.date.strftime('%A, %B, %d')%></td>
              </tr>  
              <tr>
              <td colspan="4"><strong>Time:</strong> <%=workout.duration%> | <strong>Notes:</strong> <%=workout.notes%></td>
              </tr>
              <tr>
              <td colspan="4"><button class="showrows">Show Details</button>
                  <button class="hiderows">Hide Details</button></td>
               </tr>
                </thead>
                <tbody class="test">
             <tr class="1">
               <th style="text-align: center">Exercise</th>
               <th style="text-align: center">Sets</th>
               <th style="text-align: center">Reps</th>
               <th style="text-align: center">Weight(lbs)</th>
            </tr>
               <% workout.worksets.each do |workset| %>
            <tr class="1">
               <td style="text-align: center"><%= workset.exercise.name %></td>
               <td style="text-align: center"><%= workset.sets %></td>
               <td style="text-align: center"><%= workset.reps %></td>
               <td style="text-align: center"><%= workset.weight %></td>
               <% end %>
            </tr>

             <% end %>
 
          </tbody>
        </table>

      </div>
    </div>
  </div>
     </div>
  </div>
</section>

app/views/workouts/new.html.erb
<% content_for :header do %>

       </div>
     </div>
   </section>
         <%end%>
<section class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h3 class="title">
         WORKOUT BUILDER </h3>
  <div class="column is-left">
    <div class="column is-4">
      <div class="workout-form-group">


        <h2><strong>CREATE A NEW WORKOUT</strong></h2>

        <%= form_tag new_workout_path, method: "get" do %>
          <p class="conatainer">How many exercises would you like to add?</p>

          <div class="input-group workout-form-control">
            <div class="select is-rounded" >
              <div class="control">
                 <%= select_tag :exercise_num, options_for_select(1..10), class:"form-control" %>
                 <div class="input-group-append">
              </div>

              <br>
              <%= submit_tag "Add", class:"button is-light is-rounded" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>





        <% end %>
        <br>

        <%= render 'form' %>

app/views/workouts/show.html.erb
<section class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h3 class="title">
        <%= @workout.name %>
      </h3>
      <h4 class="subtitle">
        <%= @workout.date.strftime('%A, %B, %d')%>
        </h4>
  



      <h3><strong> DURATION:</strong> <%= @workout.duration %></h3>
        <h3><strong> NOTES: </strong><%= @workout.notes%></h3>
<br>

    <table class="table is-bordered is-striped is-narrow is-hoverable ">
      <thead>
        <tr>
          <th style="text-align: center">Exercise</th>
          <th style="text-align: center">Sets</th>
          <th style="text-align: center">Reps</th>
          <th style="text-align: center">Weight(lbs)</th>
        </tr>
      </thead>
      <tbody>
        <% @workout.worksets.each do |workset| %>
        <tr>
          <td style="text-align: center"><%= workset.exercise.name %></td>

          <td style="text-align: center"><%= workset.sets %></td>
          <td style="text-align: center"><%= workset.reps %></td>
          <td style="text-align: center"><%= workset.weight %></td>

          <% end %>

        </tr>
      </tbody>
    </table>


    <% if @user.id == current_user.id %>
      <div class="btn-group">
        <%= link_to "Edit Workout", edit_workout_path(@workout), class:"button is-light is-rounded" %>
        <%= link_to "Add Exercise", new_workout_workset_path(@workout), class:"button is-light is-rounded" %>
        <%= link_to "Delete", workout_path(@workout),
                    method: :delete,
                    data: {confirm: "Are you sure you want to delete?"},
                    class:"button is-danger is-rounded" %>
      </div>
    <% end %>
  </div>
</div>
  </div>
  </div>
</section>

app/views/worksets/index.html.erb
<% content_for :header do %>
<section class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h3 class="title">
        <%= @workout.name %>
      </h3>
      <h4 class="subtitle">
        <%= @workout.date.strftime('%A, %B, %d')%>
        </h4>
    </div>
  </div>
</section>
<% end %>
<br>

      <h3><strong> DURATION:</strong> <%= @workout.duration %></h3>
        <h3><strong> NOTES: </strong><%= @workout.notes%></h3>
<br>

    <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
      <thead>
        <tr>
          <th style="text-align: center">Exercise</th>
          <th style="text-align: center">Sets</th>
          <th style="text-align: center">Reps</th>
          <th style="text-align: center">Weight(lbs)</th>
        </tr>
      </thead>
      <tbody>
        <% @workout.worksets.each do |workset| %>
        <tr>
          <td style="text-align: center"><%= workset.exercise.name %></td>

          <td style="text-align: center"><%= workset.sets %></td>
          <td style="text-align: center"><%= workset.reps %></td>
          <td style="text-align: center"><%= workset.weight %></td>

          <% end %>

        </tr>
      </tbody>
    </table>



      <div class="btn-group">
        <%= link_to "Edit Workout", edit_workout_path(@workout), class:"button is-dark is-rounded" %>
        <%= link_to "Add Exercise", new_workout_workset_path(@workout), class:"button is-dark is-rounded" %>
        <%= link_to "Delete", workout_path(@workout),
                    method: :delete,
                    data: {confirm: "Are you sure you want to delete?"},
                    class:"button is-dark is-rounded" %>
      </div>

  </div>
</div>

app/views/worksets/new.html.erb
<section class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h4 class="title">
        ADD EXERCISE
      </h4>
      <h4 class="subtitle">

        </h4>

    <div class="columns is-left">
      <div class="column is-4">

<%= simple_form_for ([@workout, @workset]) do |w| %>


  <%= w.fields_for :exercise do |exercise_form| %>
    <%= render 'workouts/exercise_fields', f: exercise_form %>
  <% end %>
  <%= w.input :sets, placeholder:"Sets",  required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false, label_html: { class: "label" } %>
  <%= w.input :reps, placeholder:"Reps",  required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false, label_html: { class: "label" } %>
  <%= w.input :weight, placeholder:"Weight",  required: true, autofocus: true, input_html: { class: "input is-rounded"}, wrapper: false, label_html: { class: "label" } %>



<br></br>
<%=  w.button :submit, "Submit", class:"button is-light is-rounded" %>
<%end%>
</div>
</div>
</div>
  </div>
  </div>
</section>

app/views/worksets/show.html.erb
<% content_for :header do %>
<section class="hero is-dark is-bold">
  <div class="hero-body">
    <div class="container">
      <h3 class="title">
        <%= @workout.name %>
      </h3>
      <h4 class="subtitle">
        <%= @workout.date.strftime('%A, %B, %d')%>
        </h4>
    </div>
  </div>
</section>
<% end %>
<br>

      <h3><strong> DURATION:</strong> <%= @workout.duration %></h3>
        <h3><strong> NOTES: </strong><%= @workout.notes%></h3>
<br>

    <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
      <thead>
        <tr>
          <th style="text-align: center">Exercise</th>
          <th style="text-align: center">Sets</th>
          <th style="text-align: center">Reps</th>
          <th style="text-align: center">Weight(lbs)</th>
        </tr>
      </thead>
      <tbody>

        <tr>
          <td style="text-align: center"><%= @workset.exercise.name %></td>

          <td style="text-align: center"><%= @workset.sets %></td>
          <td style="text-align: center"><%= @workset.reps %></td>
          <td style="text-align: center"><%= @workset.weight %></td>



        </tr>
      </tbody>
    </table>



      <div class="btn-group">
        <%= link_to "Full Workout", workout_worksets_path(@workout), class:"button is-dark is-rounded" %>

      </div>

  </div>
</div>